### ISSUE TITLE
🐛 Bug: Cannot find module '@copilotkit/runtime' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by davidko5** [CopilotKit/CopilotKit#1076]
### ♻️ Reproduction Steps

1. After updating to 1.4.1 I can not import  CopilotRuntime, copilotRuntimeNestEndpoint, GoogleGenerativeAIAdapter from '@copilotkit/runtime' as this folder doesn't exist anymore

### ✅ Expected Behavior

I expect to be able to import those from copilotkit package

### ❌ Actual Behavior

i get this error : Cannot find module '@copilotkit/runtime' or its corresponding type declarations.ts(2307)

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/react-core@1.4.1
├── @copilotkit/react-ui@1.4.1
```

**Comment by davidko5** [comment]
Didn't notice documentation update
now  @copilotkit/runtime needs to be separately

**Comment by shivmohith** [comment]
@davidko5 I am facing the same issue, can you point me to the documentation?

**Comment by davidko5** [comment]
> @davidko5 I am facing the same issue, can you point me to the documentation?
> 
> 
> 
> I installed separately but still facing the same issue

https://docs.copilotkit.ai/quickstart#install-dependencies-1

Pay attention to install dependencies section. You may need to scroll horizontally

**Comment by NathanTarbert** [comment]
@shivmohith, what version are you running?
