### ISSUE TITLE
🐛 Bug: setSuggestions not working in 1.9.3

### ISSUE THREAD

**Issue by Mid0Riii** [CopilotKit/CopilotKit#2206]
### ♻️ Reproduction Steps

`import { CopilotKit, useCopilotAction, useCopilotChat } from '@copilotkit/react-core';`
`const { setSuggestion } = useCopilotChat();`

Property 'setSuggestion' does not exist on type 'UseCopilotChatReturn'

### ✅ Expected Behavior

[Document](https://docs.copilotkit.ai/reference/hooks/useCopilotChat) mentioned that the hook `useCopilotChat` has a method called `setSuggestion`, which enable user to manully set suggestions.

### ❌ Actual Behavior

Dosen't working in version 1.9.3, the hook has no property named `setSuggestion`.

### 𝌚 CopilotKit Version

```shell
├── @copilotkit/react-core@1.9.3
├── @copilotkit/react-ui@1.9.3
```

### 📄 Logs (Optional)

```shell

```

**Comment by jpr5** [comment]
Closing. `setSuggestions` was removed from the public `useCopilotChat` type. Use `useCopilotChatSuggestions` hook instead.

**Comment by jpr5** [comment]
Closing. `setSuggestions` was removed from the public `useCopilotChat` type. Use `useCopilotChatSuggestions` hook instead.

**Comment by jpr5** [comment]
Closing. `setSuggestions` was removed from the public `useCopilotChat` type. Use `useCopilotChatSuggestions` hook instead.

**Comment by jpr5** [comment]
Closing. `setSuggestions` was removed from the public `useCopilotChat` type. Use `useCopilotChatSuggestions` hook instead.
