### ISSUE TITLE
Is there a way to make copilotkit pysdk 0.1.53 support langgraph 0.5+?

### ISSUE THREAD

**Issue by WinnieZYC** [CopilotKit/CopilotKit#2092]
I was using langgraph-supervisor and needed to create some agent objects using create_react_agent but was prompted that it couldn't handle input_schema, when I upgraded langgraph to 0.5.0+ this error was resolved but this is not the same as the copiliotKit. However, this conflicts with copiliotKit's restriction on langgraph version to less than 0.5.0, is there any way to make the two compatible, or is there any way I can accomplish this. Here are some error messages and the original code:

When langgraph==0.4.10:
`    clean_agent = create_react_agent(
        model=llm,
        tools=clean_tools,
        prompt=CLEAN_AGENT_SYSTEM_PROMPT,
        name="clean_agent"
    )`
`TypeError: StateGraph.add_node() got an unexpected keyword argument 'input_schema'`

When langgraph==0.5.1:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
copilotkit 0.1.53 requires langgraph<0.5.0,>=0.3.18, but you have langgraph 0.5.1 which is incompatible.`

**Comment by WinnieZYC** [comment]
已经收到，谢谢您

**Comment by vcygni** [comment]
@WinnieZYC have you found a solution to this?

Are there any update on this issue?

**Comment by yonatangross** [comment]
any update?

**Comment by WinnieZYC** [comment]
Yet not. I look up some issues about _create_react_agent_ in copilotKit, and I 'm not sure that CopilotKit itself doesn't support the _create_react_agent_.

**Comment by WinnieZYC** [comment]
Not yet. I have looked up some issues about create_react_agent in copilotKit, and I 'm not sure that CopilotKit itself doesn't support the create_react_agent.

**Comment by cvolante54** [comment]
I just ran into the same issue, and I know it's not the best solution, but pinning the `langgraph-prebuilt` to version `0.2.3` solved it for me

**Comment by vcygni** [comment]
> I just ran into the same issue, and I know it's not the best solution, but pinning the `langgraph-prebuilt` to version `0.2.3` solved it for me

`Because langgraph (0.5.0) depends on langgraph-prebuilt (>=0.5.0)
 and ******* depends on langgraph-prebuilt (0.2.3), langgraph is forbidden.
So, because ******* depends on langgraph (0.5.0), version solving failed.`

how does it work for you @cvolante54 ?

also there is a bug with the v0.5.0 version of langgraph : [issue](https://github.com/langchain-ai/langgraph/issues/5658)

so langgraph v0.5.3+ has a **fix** but then that's not yet even available with copilotkit v0.1.56.

**Comment by baswenneker** [comment]
This is nuts, why doesnt this get any attention? Copilotkit doesnt work with langgraph atm!

**Comment by cvolante54** [comment]
@cygniv404 I'm using langraph `0.4.10`, I'm treating the copilotkit dependency as `langgraph = ">=0.3.18,<0.5.0"` since there is no way to get patch fixes.

**Comment by cassandre-voisin** [comment]
Hello, 
 any update on this ? We would love to use langgraph 0.6

**Comment by jpr5** [comment]
Correcting our earlier triage — LangGraph 0.5+ IS natively supported. The current SDK specifies `langgraph >= 0.3.25, < 2` in pyproject.toml, covering 0.5+, 0.6+, and 1.x. Our previous claim that 'no native 0.5+ support has landed' was factually wrong. Closing as already implemented — this works today.

**Comment by WinnieZYC** [comment]
已经收到，谢谢您
