### ISSUE TITLE
start runtime server crash

### ISSUE THREAD

**Issue by itzhoujun** [CopilotKit/CopilotKit#3463]
start runtime server crash when upgrading from 1.51.2 to 1.54.0
```
> tsx server/server.ts

node:internal/modules/cjs/loader:1383
  const err = new Error(message);
              ^

Error: Cannot find module './src/core'
Require stack:
- /Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/fast-json-patch@3.1.0/node_modules/fast-json-patch/index.ts
    at node:internal/modules/cjs/loader:1383:15
    at nextResolveSimple (/Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1004)
    at /Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-D46fvsV_.cjs:3:2630
    at /Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-D46fvsV_.cjs:3:1542
    at resolveTsPaths (/Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-D46fvsV_.cjs:4:760)
    at /Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1102
    at m._resolveFilename (file:///Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/tsx@4.21.0/node_modules/tsx/dist/register-B7jrtLTO.mjs:1:789)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zhoujun/develope/code/vegin/vegin-agent-platform/frontend/node_modules/.pnpm/fast-json-patch@3.1.0/node_modules/fast-json-patch/index.ts'
  ]
}

Node.js v22.22.0
```

tsx server.ts:
```typescript
import express from 'express';
import {
    CopilotRuntime,
    ExperimentalEmptyAdapter,
    copilotRuntimeNodeExpressEndpoint,
} from "@copilotkit/runtime";
import { LangGraphHttpAgent } from '@copilotkit/runtime/langgraph';

const serviceAdapter = new ExperimentalEmptyAdapter()

const baseUrl = "http://localhost:9998";

const runtime = new CopilotRuntime({
    agents: {
        ai_writer: new LangGraphHttpAgent({
            url: `${baseUrl}/agents/ai_writer`,
        }),
        clip_mind: new LangGraphHttpAgent({
            url: `${baseUrl}/agents/clip_mind`,
        }),
    },
});

const copilotRuntime = copilotRuntimeNodeExpressEndpoint({
    endpoint: "/",
    runtime,
    serviceAdapter,
});
const app = express();

app.use("/api/copilotkit", copilotRuntime);

const port = Number(process.env.PORT || 3001);
app.listen(port, () => console.log(`Server listening on http://127.0.0.1:${port}`));


```
copilotkit version: 1.54.0

**Comment by jpr5** [comment]
This is a `fast-json-patch` + `tsx` loader issue in your toolchain, not CopilotKit. Pin `tsx` to a newer version or use `ts-node`. Closing as environment issue.
